### ISSUE TITLE
Deletion of non-existent product

### ISSUE THREAD

**Issue by niveditashankaranarayanan** [CSCI-GA-2820-FA24-003/products#20]
**As a** developer,
**I need** to ensure that the system responds correctly when attempting to delete a product that does not exist,
**So that** the API returns the appropriate 404 Not Found error and informs the user that the product does not exist.

**Details and Assumptions**

- The delete request should use a non-existent product ID to simulate the scenario.
- If the product does not exist, the system should return a 404 status code.
- The response should include a clear error message that specifies the product could not be found.

**Acceptance Criteria:**

```
Given a delete request with a non-existent product ID,
When I attempt to delete the product,
Then the system should return a 404 Not Found status code and a message saying "Product with id {non_existent_product_id} not found."

```

**Comment by savarchaturvedi** [comment]
updated the story with correct format.
