### ISSUE TITLE
Remove Flask Migration Dependency

### ISSUE THREAD

**Issue by NBFYayI** [CSCI-GA-2820-FA24-003/products#3]
**As a developer** I need to remove the unnecessary Flask migration dependency,
**So that** the project stays clean and does not rely on unneeded tools.

**Details and Assumptions**

- Flask migration is currently not being used or needed for database management.
- Removing the dependency will simplify the codebase and reduce potential conflicts.
- The removal should not affect existing database functionality.

**Acceptance Criteria**
```
Given the Flask migration dependency exists in the system,
When I remove the migration setup,
Then the application should run without errors, and the database should remain functional.
```

**Comment by savarchaturvedi** [comment]
this is a duplicate issue, hence closing it.
