### ISSUE TITLE
Filtering products by price range: 

### ISSUE THREAD

**Issue by NBFYayI** [CSCI-GA-2820-FA24-003/products#4]
**As a developer I need** the ability to request products within a specified minimum and maximum price range. **So that** I can use minPrice and maxPrice query parameters to create feature for user to use.

**Details and Assumptions**
    The product api should allow price range with minimum and maximum.
    The read function should include min and max parameters and if no products in this range return 404 error.

**Acceptance Criteria**
Given a price range with min and max,
When I read the products
Then the products within the range are returned correctly

**Comment by savarchaturvedi** [comment]
duplicate issue, hence closing it.

**Comment by niveditashankaranarayanan** [comment]
This I believe could be done for next sprint.

**Comment by savarchaturvedi** [comment]
this is duplicate
