### ISSUE TITLE
Add functionality to models to handle different data

### ISSUE THREAD

**Issue by NBFYayI** [CSCI-GA-2820-FA24-003/products#6]
**As a** Backend Developer
**I need** clearer functionality in model
**So that** I can understand what will happen when users do things incorrectly.

**Details and Assumptions:**
- Create functionality and error handling for invalid data and situation.
- Understand the exact problem.
- Return with the correct error code and error message.

**Acceptance Criteria:**

```

Given there are invalid data input  
When a model function is called  
Then the function will return different errors status and message base on situation

```

**Comment by savarchaturvedi** [comment]
duplicate issue, hence closing it.
