### ISSUE TITLE
Design the Products Database Schema

### ISSUE THREAD

**Issue by niveditashankaranarayanan** [CSCI-GA-2820-FA24-003/products#7]
**As a** Backend Developer
**I need** to set up a product database
**So that** I can store and manage product details for future CRUDL operations.

**Details and Assumptions:**

* The database schema must include the following fields: id (SKU), name, description, and price.
* The SKU must be unique for each product.
* The price field should be stored as a Numeric or Decimal value (not as a Float).
* Database design must support indexing on the SKU field for performance.
* Role-based access control (RBAC) should be implemented for security.
* The database will be set up in the development environment to ensure it supports CRUDL operations:
* **Create:** Ability to add new products to the database.
*  **Read:** Ability to retrieve products from the database.
*  **Update:** Ability to modify existing product details.
*  **Delete:** Ability to remove products from the database.
*  **List:** Ability to list all products available in the database.

**Acceptance Criteria**
```
Given the product database schema is successfully created with the necessary fields (SKU, name, description, price)  
When valid product data (including SKU, name, description and price) is provided for the Create operation  
Then the API successfully creates the product and returns a 201 Created status with the full details of the created product (e.g., SKU, name, description, price).

When any of the required fields (SKU, name, description or price) are missing or invalid  
Then the API returns a 400 Bad Request error.

When a product with the same SKU already exists in the database  
Then the API returns a 409 Conflict error, ensuring SKU uniqueness.

Then the database should support the other CRUDL operations (Read, Update, Delete, List) after setup.
```

**Comment by niveditashankaranarayanan** [comment]
As a developer, I need to design the database schema for products, so that products can be stored and managed in the system.

Tasks:
- Create a table for Products with the following fields: SKU (unique), name, description, price (decimal), and created_at timestamp.
- Ensure SKU is a unique identifier.
- Set up database migrations to create the Products table.

Acceptance Criteria:
- The Products table is created in the database with all necessary fields.
- The SKU field is unique across all products.

**Comment by savarchaturvedi** [comment]
Duplicate story, closing it.

**Comment by niveditashankaranarayanan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-fa24-003-66e8cda54e53130017251e62/issues/CSCI-GA-2820-FA24-003/products/7?planning-poker) with Zenhub @HRHRHRHR666 @YiTongG @NBFYayI @savarchaturvedi

**Comment by niveditashankaranarayanan** [comment]
Thank you for refining the title; it's now much clearer and to the point.
