### ISSUE TITLE
Update a product:  Update Product API

### ISSUE THREAD

**Issue by YiTongG** [CSCI-GA-2820-FA24-003/products#8]
**As a** Product Manager
**I need** the ability to update product details (e.g., name, description, price, and stock)
**So that** I can ensure product information is always current and accurate.

   
 ### Details and Assumptions
* Implement the PUT /update API endpoint to update product details.
* Validation must be included (e.g., price cannot be negative, SKU must be an integer).
* Changes should be reflected in real-time in the database and on the product listing page.

**Acceptance Criteria**
**Scenario:** Updating a product's details 
 
```
Given a product exists in the system  
When I edit the product name, description, price, or stock  
Then the updated values are saved and displayed correctly in the system.
```

**Comment by niveditashankaranarayanan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-fa24-003-66e8cda54e53130017251e62/issues/CSCI-GA-2820-FA24-003/products/8?planning-poker) with Zenhub @YiTongG @NBFYayI @HRHRHRHR666 @savarchaturvedi

**Comment by niveditashankaranarayanan** [comment]
As per our discussion, made sure updating root URL, README.md is carried out.
